import csv
from geopy.geocoders import Nominatim

# List of communes in Bern
communes = [
     "Aarberg",
    "Bargen (BE)",
    "Grossaffoltern",
    "Kallnach",
    "Kappelen",
    "Lyss",
    "Meikirch",
    "Radelfingen",
    "Rapperswil (BE)",
    "Schüpfen",
    "Seedorf (BE)",
    "Aarwangen",
    "Auswil",
    "Bannwil",
    "Bleienbach",
    "Busswil bei Melchnau",
    "Gondiswil",
    "Langenthal",
    "Lotzwil",
    "Madiswil",
    "Melchnau",
    "Oeschenbach",
    "Reisiswil",
    "Roggwil (BE)",
    "Rohrbach",
    "Rohrbachgraben",
    "Rütschelen",
    "Schwarzhäusern",
    "Thunstetten",
    "Ursenbach",
    "Wynau",
    "Bern",
    "Bolligen",
    "Bremgarten bei Bern",
    "Kirchlindach",
    "Köniz",
    "Muri bei Bern",
    "Oberbalm",
    "Stettlen",
    "Vechigen",
    "Wohlen bei Bern",
    "Zollikofen",
    "Ittigen",
    "Ostermundigen",
    "Biel/Bienne",
    "Evilard",
    "Arch",
    "Büetigen",
    "Büren an der Aare",
    "Diessbach bei Büren",
    "Dotzigen",
    "Lengnau (BE)",
    "Leuzigen",
    "Meienried",
    "Meinisberg",
    "Oberwil bei Büren",
    "Pieterlen",
    "Rüti bei Büren",
    "Wengi",
    "Aefligen",
    "Alchenstorf",
    "Bäriswil",
    "Burgdorf",
    "Ersigen",
    "Hasle bei Burgdorf",
    "Heimiswil",
    "Hellsau",
    "Hindelbank",
    "Höchstetten",
    "Kernenried",
    "Kirchberg (BE)",
    "Koppigen",
    "Krauchthal",
    "Lyssach",
    "Oberburg",
    "Rüdtligen-Alchenflüh",
    "Rumendingen",
    "Rüti bei Lyssach",
    "Willadingen",
    "Wynigen",
    "Corgémont",
    "Cormoret",
    "Cortébert",
    "Courtelary",
    "La Ferrière",
    "Mont-Tramelan",
    "Orvin",
    "Renan (BE)",
    "Romont (BE)",
    "Saint-Imier",
    "Sonceboz-Sombeval",
    "Sonvilier",
    "Tramelan",
    "Villeret",
    "Sauge",
    "Péry-La Heutte",
    "Brüttelen",
    "Erlach",
    "Finsterhennen",
    "Gals",
    "Gampelen",
    "Ins",
    "Lüscherz",
    "Müntschemier",
    "Siselen",
    "Treiten",
    "Tschugg",
    "Vinelz",
    "Bätterkinden",
    "Deisswil bei Münchenbuchsee",
    "Diemerswil",
    "Fraubrunnen",
    "Jegenstorf",
    "Iffwil",
    "Mattstetten",
    "Moosseedorf",
    "Münchenbuchsee",
    "Urtenen-Schönbühl",
    "Utzenstorf",
    "Wiggiswil",
    "Wiler bei Utzenstorf",
    "Zielebach",
    "Zuzwil (BE)",
    "Adelboden",
    "Aeschi bei Spiez",
    "Frutigen",
    "Kandergrund",
    "Kandersteg",
    "Krattigen",
    "Reichenbach im Kandertal",
    "Beatenberg",
    "Bönigen",
    "Brienz (BE)",
    "Brienzwiler",
    "Därligen",
    "Grindelwald",
    "Gsteigwiler",
    "Gündlischwand",
    "Habkern",
    "Hofstetten bei Brienz",
    "Interlaken",
    "Iseltwald",
    "Lauterbrunnen",
    "Leissigen",
    "Lütschental",
    "Matten bei Interlaken",
    "Niederried bei Interlaken",
    "Oberried am Brienzersee",
    "Ringgenberg (BE)",
    "Saxeten",
    "Schwanden bei Brienz",
    "Unterseen",
    "Wilderswil",
    "Arni (BE)",
    "Biglen",
    "Bowil",
    "Brenzikofen",
    "Freimettigen",
    "Grosshöchstetten",
    "Häutligen",
    "Herbligen",
    "Kiesen",
    "Konolfingen",
    "Landiswil",
    "Linden",
    "Mirchel",
    "Münsingen",
    "Niederhünigen",
    "Oberdiessbach",
    "Oberthal",
    "Oppligen",
    "Rubigen",
    "Walkringen",
    "Worb",
    "Zäziwil",
    "Oberhünigen",
    "Allmendingen",
    "Wichtrach",
    "Clavaleyres",
    "Ferenbalm",
    "Frauenkappelen",
    "Gurbrü",
    "Kriechenwil",
    "Laupen",
    "Mühleberg",
    "Münchenwiler",
    "Neuenegg",
    "Wileroltigen",
    "Belprahon",
    "Champoz",
    "Corcelles (BE)",
    "Court",
    "Crémines",
    "Eschert",
    "Grandval",
    "Loveresse",
    "Moutier",
    "Perrefitte",
    "Reconvilier",
    "Roches (BE)",
    "Saicourt",
    "Saules (BE)",
    "Schelten",
    "Seehof",
    "Sorvilier",
    "Tavannes",
    "Rebévelier",
    "Petit-Val",
    "Valbirse",
    "La Neuveville",
    "Nods",
    "Plateau de Diesse",
    "Aegerten",
    "Bellmund",
    "Brügg",
    "Bühl",
    "Epsach",
    "Hagneck",
    "Hermrigen",
    "Jens",
    "Ipsach",
    "Ligerz",
    "Merzligen",
    "Mörigen",
    "Nidau",
    "Orpund",
    "Port",
    "Safnern",
    "Scheuren",
    "Schwadernau",
    "Studen (BE)",
    "Sutz-Lattrigen",
    "Täuffelen",
    "Walperswil",
    "Worben",
    "Twann-Tüscherz",
    "Därstetten",
    "Diemtigen",
    "Erlenbach im Simmental",
    "Oberwil im Simmental",
    "Reutigen",
    "Spiez",
    "Wimmis",
    "Stocken-Höfen",
    "Guttannen",
    "Hasliberg",
    "Innertkirchen",
    "Meiringen",
    "Schattenhalb",
    "Boltigen",
    "Lenk",
    "St. Stephan",
    "Zweisimmen",
    "Gsteig",
    "Lauenen",
    "Saanen",
    "Guggisberg",
    "Rüschegg",
    "Schwarzenburg",
    "Belp",
    "Burgistein",
    "Gerzensee",
    "Gurzelen",
    "Jaberg",
    "Kaufdorf",
    "Kehrsatz",
    "Kirchdorf (BE)",
    "Niedermuhlern",
    "Riggisberg",
    "Rüeggisberg",
    "Seftigen",
    "Toffen",
    "Uttigen",
    "Wattenwil",
    "Wald (BE)",
    "Thurnen",
    "Eggiwil",
    "Langnau im Emmental",
    "Lauperswil",
    "Röthenbach im Emmental",
    "Rüderswil",
    "Schangnau",
    "Signau",
    "Trub",
    "Trubschachen",
    "Amsoldingen",
    "Blumenstein",
    "Buchholterberg",
    "Eriz",
    "Fahrni",
    "Heiligenschwendi",
    "Heimberg",
    "Hilterfingen",
    "Homberg",
    "Horrenbach-Buchen",
    "Oberhofen am Thunersee",
    "Oberlangenegg",
    "Pohlern",
    "Sigriswil",
    "Steffisburg",
    "Teuffenthal (BE)",
    "Thierachern",
    "Thun",
    "Uebeschi",
    "Uetendorf",
    "Unterlangenegg",
    "Wachseldorn",
    "Zwieselberg",
    "Forst-Längenbühl",
    "Affoltern im Emmental",
    "Dürrenroth",
    "Eriswil",
    "Huttwil",
    "Lützelflüh",
    "Rüegsau",
    "Sumiswald",
    "Trachselwald",
    "Walterswil (BE)",
    "Wyssachen",
    "Attiswil",
    "Berken",
    "Bettenhausen",
    "Farnern",
    "Graben",
    "Heimenhausen",
    "Herzogenbuchsee",
    "Inkwil",
    "Niederbipp",
    "Niederönz",
    "Oberbipp",
    "Ochlenberg",
    "Rumisberg",
    "Seeberg",
    "Thörigen",
    "Walliswil bei Niederbipp",
    "Walliswil bei Wangen",
    "Wangen an der Aare",
    "Wangenried",
    "Wiedlisbach"
]

def scrape_geodata(communes):
    geolocator = Nominatim(user_agent="commune_geodata_scraper")
    print(len(communes))
    
    with open("communes_geodata.csv", "w", newline="") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(["Commune Name", "Latitude", "Longitude"])
        
        for commune in communes:
            location = geolocator.geocode(commune + ", Bern, Switzerland")
            
            if location is not None:
                writer.writerow([commune, location.latitude, location.longitude])
                print(f"Scraped data for {commune}")
            else:
                writer.writerow([commune, "", ""])
                print(f"Unable to scrape data for {commune}")

scrape_geodata(communes)
